# Generated by Django 5.0.2 on 2024-03-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_photo_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='image.jpg', upload_to=''),
        ),
    ]
