# Generated by Django 5.0.2 on 2024-03-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='like',
        ),
    ]
