# Generated by Django 5.0.2 on 2024-03-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_is_allowed_alter_comments_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_allowed',
            field=models.BooleanField(blank=True),
        ),
    ]
