# Generated by Django 5.0.2 on 2024-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_subuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='about',
            field=models.TextField(blank=True, default='Расскажите о себе'),
        ),
    ]
